#!/usr/bin/env bash
#Setup web server for web static deployment

sudo apt-get update
sudo apt-get install nginx -y
mkdir -p /data/web_static/shared
mkdir -p /data/web_static/releases/test
echo '<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>AirBnB clone</title>
    </head>
    <body style="margin: 0px; padding: 0px;">
        <header style="height: 70px; width: 100%; background-color: #FF0000">
</header>

<footer style="position: absolute; left: 0; bottom: 0; height: 60px; width: 100%; background-color: #00FF00; text-align: center; overflow: hidden;">
<p style="line-height: 60px; margin: 0px;">Holberton School</p>
</footer>
</body>
</html>' > /data/web_static/releases/test/index.html
rm -f /data/web_static/current
ln -s /data/web_static/releases/test/ /data/web_static/current
chown -R ubuntu /data/
chgrp -R ubuntu /data/
printf %s "server {
       listen 80 default_server;
       listen [::]:80;
       add_header X-Served-By $HOSTNAME;
       root /var/www/html;
       index index.html index.htm index.debian.html;
location /hbnb_static{
	 alias /data/web_static/current;
	 index index.html index.htm;
       }
location /redirect_me{
	 return 301 https://github.com/mire-web;
       }
       error_page 404 /404.html;
location /404 {
	 root /var/www/html;
	 internal;
       }
}" > /etc/nginx/sites-available/default
sudo service nginx restart

